##  CONFIG
outDir: "results/2025_0322_scE2G_fine_grained"
methodsTable: "config/mine/config_methods_example.tsv"
predictionsTable: "config/mine/config_predictions_example.tsv"
methods: [scE2G_multiome, scE2G_ATAC, Kendall, scABC, ABC_distanceToTSS, SnapATAC, Cicero, FigR, ScenicPlus, DIRECTNET, ArchR]
eQTLVariants: "/oak/stanford/groups/engreitz/Users/sheth/Data/eQTL_Catalogue_v7/results/2024_1003_fine_tissues/eQTL_catalogue_v7.processed.PIP0.5.tsv.gz" # columns: chr,start,end,variant_id,gene_hgnc,tissue,pip

## RESOURCE / REFERENCE FILES
baseDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/"
# Genome annotations
chrSizes: "resources/genome_annotation/GRCh38_EBV.chrom.sizes.tsv" 
partition: "resources/genome_annotation/PartitionCombined.bed" 
TSS_reference: "resources/genome_annotation/CollapsedGeneBounds.hg38.intGENCODEv43.TSS500bp.bed6" 
# Background variants
bgVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/backgroundSNPs/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted"

## PARAMETERS
distances: [10, 100, 250, 1000] # in kb
recalls: [0.03, 0.05, 0.1] # to compare enrichments
thresholdPIP: 0.5
thresholdPval: 0.05
nThresholdSteps: 50





