# FILE LOCATIONS
outDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-byBiosample/eQTLEnrichment/workflow/2021_1130_threshold"
codeDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-byBiosample/eQTLEnrichment/workflow/scripts"
envDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-byBiosample/eQTLEnrichment/workflow/envs"
methodsTable: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-byBiosample/eQTLEnrichment/config/config-baseline-predictors.tsv"
GTExVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/GTExVariants/GTEx_30tissues_hg38.tsv.gz"
bgVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/backgroundSNPs/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted"
chrSizes: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/hg38.chrom.sizes"
partition: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/genomePartition/2021_1020_results_allPermutations/PartitionCombined.bed"
TSS: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/GENCODEv29/gencode.v29.transcripts.level12.basic.protein_coding.TSS500bp.bed"

# GTEx expression data
GTExExpression: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment/resources/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct"
GTExGeneUniverse: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/GTExCollapsedAnnotations/gencode.v26.genes.collapsed.bed"

# list of methods to run
methods: [dist_to_gene, dist_to_tss, nearest_gene, nearest_tss, reads_by_dist_to_tss_norm, reads_by_dist_to_tss, within_100kb_of_tss]

GTExTissues: [Brain_Cortex, Prostate, Muscle_Skeletal, Artery_Tibial, Skin_Not_Sun_Exposed_Suprapubic, Esophagus_Muscularis, Brain_Cerebellum, Pituitary, Adipose_Subcutaneous, Pancreas, Spleen, Adrenal_Gland, Testis, Lung, Skin_Sun_Exposed_Lower_leg, Heart_Atrial_Appendage, Adipose_Visceral_Omentum, Esophagus_Mucosa, Thyroid, Brain_Nucleus_accumbens_basal_ganglia, Colon_Sigmoid, Breast_Mammary_Tissue, Artery_Aorta, Cells_EBV-transformed_lymphocytes, Heart_Left_Ventricle, Artery_Coronary, Esophagus_Gastroesophageal_Junction, Nerve_Tibial, Liver, Whole_Blood, Colon_Transverse, Stomach]

