## FILE LOCATIONS

outDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment/workflow/results_rep1genes"
codeDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment/workflow/scripts"
GTExVariants: "/oak/stanford/groups/engreitz/Projects/GWAS/data/Ulirsch-eQTL/200207/GTEx_30tissues_release1.tsv.gz"
bgVariants: "/oak/stanford/groups/engreitz/Projects/GWAS/210208_Benchmarking/data/all.bg.SNPs.sorted.bed.gz"
chrSizes: "/oak/stanford/groups/engreitz/Projects/GWAS/201216_ABCPipelineTest/Test_data/sizes_sorted"
partition: "/oak/stanford/groups/engreitz/Projects/GWAS/191223_Partitioning/200523-ABCPartition/partition/PartitionCombined.bed"
genes: "/oak/stanford/groups/engreitz/Users/sheth/eQTLPredictions/RefSeqCurated.170308.bed.CollapsedGeneBounds.sorted.bed"
geneFilter: "/oak/stanford/groups/engreitz/Users/sheth/GM12878Expression/rep1_genelist.tsv"
TSS: "/oak/stanford/groups/engreitz/Users/sheth/eQTLPredictions/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS500bp.sorted.bed"


## METHODS AND METHOD-SPECIFIC PARAMETERS
# list of methods to run
methods: [ABCShrunk500, EpiMap, ChromHMM2017]
GTExTissues: [Brain_Cortex, Prostate, Muscle_Skeletal, Artery_Tibial, Skin_Not_Sun_Exposed_Suprapubic, Esophagus_Muscularis, Brain_Cerebellum, Pituitary, Adipose_Subcutaneous, Pancreas, Spleen, Adrenal_Gland, Testis, Lung, Skin_Sun_Exposed_Lower_leg, Heart_Atrial_Appendage, Adipose_Visceral_Omentum, Esophagus_Mucosa, Thyroid, Brain_Nucleus_accumbens_basal_ganglia, Colon_Sigmoid, Breast_Mammary_Tissue, Artery_Aorta, Cells_EBV-transformed_lymphocytes, Heart_Left_Ventricle, Artery_Coronary, Esophagus_Gastroesophageal_Junction, Nerve_Tibial, Liver, Whole_Blood, Colon_Transverse, Stomach]

# gzipped prediction file locations
predFile:
 ABC: "/oak/stanford/groups/engreitz/Projects/ABC/191216_ABC/summary/AllPredictions.txt.gz"
 EpiMap: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/enhancerPredictions_Ben-all.bed.gz"
 ChromHMM2017: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/ChromHMM2017_Appended.txt.gz"
 ABCShrunk100: "/oak/stanford/groups/engreitz/Projects/GWAS/210208_Benchmarking/data/AllPredictions.AvgHiC.ABC0.015.100.txt.gz"
 ABCShrunk200: "/oak/stanford/groups/engreitz/Projects/GWAS/210208_Benchmarking/data/AllPredictions.AvgHiC.ABC0.015.200.txt.gz"
 ABCShrunk300: "/oak/stanford/groups/engreitz/Projects/GWAS/210208_Benchmarking/data/AllPredictions.AvgHiC.ABC0.015.300.txt.gz"
 ABCShrunk400: "/oak/stanford/groups/engreitz/Projects/GWAS/210208_Benchmarking/data/AllPredictions.AvgHiC.ABC0.015.400.txt.gz"
 ABCShrunk500: "/oak/stanford/groups/engreitz/Projects/GWAS/210208_Benchmarking/data/AllPredictions.AvgHiC.ABC0.015.500.txt.gz"
 

## PARAMETERS FOR INDIVIDUAL RULES
enrichment_heatmaps:
 sampleKey:
  ABC: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/CellTypes.Annotated.ABCPaper.csv"
  EpiMap: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/bssid_legend.csv"
  ChromHMM2017: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/EID-legend.csv"
  ABCShrunk100: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/CellTypes.Annotated.ABCPaper.csv"
  ABCShrunk200: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/CellTypes.Annotated.ABCPaper.csv"
  ABCShrunk300: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/CellTypes.Annotated.ABCPaper.csv"
  ABCShrunk400: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/CellTypes.Annotated.ABCPaper.csv"
  ABCShrunk500: "/oak/stanford/groups/engreitz/Users/sheth/ReferenceFiles/CellTypes.Annotated.ABCPaper.csv"

 sampleID:
  ABC: CellType
  EpiMap: BSSID
  ChromHMM2017: EID
  ABCShrunk100: CellType
  ABCShrunk200: CellType
  ABCShrunk300: CellType
  ABCShrunk400: CellType
  ABCShrunk500: CellType

 sampleName:
  ABC: NA
  EpiMap: SampleName
  ChromHMM2017: Epigenome.Mnemonic
  ABCShrunk100: NA
  ABCShrunk200: NA
  ABCShrunk300: NA
  ABCShrunk400: NA
  ABCShrunk500: NA

 sampleCategory:
  ABC: Categorical.CellTypeMergedPrimary
  EpiMap: Group
  ChromHMM2017: Group
  ABCShrunk100: Categorical.CellTypeMergedPrimary
  ABCShrunk200: Categorical.CellTypeMergedPrimary
  ABCShrunk300: Categorical.CellTypeMergedPrimary
  ABCShrunk400: Categorical.CellTypeMergedPrimary
  ABCShrunk500: Categorical.CellTypeMergedPrimary

predRates:
 mapGTExTissues:
  ABC: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  EpiMap: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  ChromHMM2017: [Cells_EBV-transformed_lymphocytes, Liver]
  ABCShrunk100: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  ABCShrunk200: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  ABCShrunk300: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  ABCShrunk400: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  ABCShrunk500: [Cells_EBV-transformed_lymphocytes, Liver, Thyroid]
  

 mapBiosamples:
  ABC: [GM12878-Roadmap, liver-ENCODE, thyroid_gland-ENCODE]
  EpiMap: [BSS00439, BSS01158, BSS01831]
  ChromHMM2017: [E116, E066]
  ABCShrunk100: [GM12878-Roadmap, liver-ENCODE, thyroid_gland-ENCODE]
  ABCShrunk200: [GM12878-Roadmap, liver-ENCODE, thyroid_gland-ENCODE]
  ABCShrunk300: [GM12878-Roadmap, liver-ENCODE, thyroid_gland-ENCODE]
  ABCShrunk400: [GM12878-Roadmap, liver-ENCODE, thyroid_gland-ENCODE]
  ABCShrunk500: [GM12878-Roadmap, liver-ENCODE, thyroid_gland-ENCODE]
  