##  CONFIG
# outDir: "results/2024_0523_fig2_test"
# methodsTable: "config/mine/config_methods_fig2_test.tsv"
# methods: [ENCODE_rE2G, ENCODE_rE2Gext, ABC_full, ABC_DNase, CIA, EPIraction, EpiMap, GraphReg, DHS_distToTSS, DHS_nearestExprGene] # list of methods from methodsTable to run

outDir: "results/2024_0528_scE2G_BMMC"
methodsTable: "config/mine/config_methods_scE2G_BMMC.tsv"
methods: [scE2G_multiome, scE2G_multiome_intx, scE2G_ATAC, scE2G_ATAC_intx, scABC, Kendall, ABC_distToTSS]

eQTLVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/GTExVariants/GTEx_30tissues_hg38.SUSIE.cs.expressedTPM1.tsv.gz"  # columns: chr,start,end,varID_hg38,gene_hgnc,tissue,pip

## RESOURCE / REFERENCE FILES
baseDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/"
# Genome annotations
chrSizes: "resources/genome_annotation/GRCh38_EBV.chrom.sizes.tsv" 
partition: "resources/genome_annotation/PartitionCombined.bed" 
TSS: "resources/genome_annotation/CollapsedGeneBounds.hg38.TSS500bp.bed" 
GTExGeneUniverse: "resources/genome_annotation/CollapsedGeneBounds.hg38.bed"
# Background variants
bgVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/backgroundSNPs/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted"

## PARAMETERS
distances: [10, 100, 250] # in kb
recalls: [0.1, 0.15] # to compare enrichments
thresholdPIP: 0.5
nThresholdSteps: 20 





