##  CONFIG
outDir: "results/2024_1024_scE2G_and_bulk"
methodsTable: "config/mine/config_methods.tsv"
predictionsTable: "config/mine/config_predictions_sc_bulk.tsv"
methods: [scE2G_multiome, scE2G_ATAC, scABC, ABC_distanceToTSS, DNase_ENCODE_rE2G, ENCODE_rE2G_extended, DNase_ABC, DNase_ABC_distanceToTSS]
eQTLVariants: "/oak/stanford/groups/engreitz/Users/sheth/Data/eQTL_Catalogue_v7/results/2024_0623_coarse_tissues/eQTL_catalogue_v7.processed.PIP0.5.tsv.gz" # columns: chr,start,end,variant_id,gene_hgnc,tissue,pip

## RESOURCE / REFERENCE FILES
baseDir: "/oak/stanford/groups/engreitz/Users/sheth/eQTLEnrichment-integrated/eQTLEnrichment/"
# Genome annotations
chrSizes: "resources/genome_annotation/GRCh38_EBV.chrom.sizes.tsv" 
partition: "resources/genome_annotation/PartitionCombined.bed" 
TSS: "resources/genome_annotation/CollapsedGeneBounds.hg38.TSS500bp.bed" 
GTExGeneUniverse: "resources/genome_annotation/CollapsedGeneBounds.hg38.bed"
# Background variants
bgVariants: "/oak/stanford/groups/engreitz/Users/sheth/hg38_resources/backgroundSNPs/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted"

## PARAMETERS
distances: [10, 100, 250, 1000] # in kb
recalls: [0.05, 0.1, 0.15] # to compare enrichments
thresholdPIP: 0.5
thresholdPval: 0.05
nThresholdSteps: 50





